"""Shared defaults for the public optimization API."""

DEFAULT_AREA_WEIGHT = 0.0
DEFAULT_LENGTH_SMOOTHNESS_WEIGHT = 1.0
DEFAULT_MAX_ITERATIONS = 10000
DEFAULT_MINIMUM_GAP = 0.03
DEFAULT_UNIFORMITY_WEIGHT = 0.0
